FROM debian:jessie
MAINTAINER Viktor Farcic "viktor@farcic.com"

ENV VERSION 1.0

# Conf
COPY apt.conf /etc/apt/
COPY environment /etc/
COPY .bowerrc /root/ 
COPY .npmrc /root/

# Setup
COPY setup_0.12 /usr/ 
RUN chmod +x /usr/setup_0.12

RUN apt-get update

# Curl
RUN apt-get -y install curl

# Dependencies
RUN /usr/setup_0.12
RUN echo "deb http://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
RUN /bin/bash -c "curl -sL --proxy http://192.168.22.1:3129 https://dl-ssl.google.com/linux/linux_signing_key.pub" | apt-key add -
RUN echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
RUN echo "deb http://packages.linuxmint.com debian import" >> /etc/apt/sources.list

# Mongo, NodeJS, Git, SBT, xvfb, FireFox, Chrome
RUN apt-get update && \
    apt-get -y --fix-missing install wget bzip2 make g++ && \
    apt-get -y --force-yes --fix-missing install --no-install-recommends mongodb nodejs git sbt xvfb firefox google-chrome-stable && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Scala
RUN curl -O -q --proxy http://192.168.22.1:3129 http://downloads.typesafe.com/scala/2.11.5/scala-2.11.5.deb && \
    dpkg -i scala-2.11.5.deb && \
    rm scala-2.11.5.deb

# Gulp, bower
RUN  npm install -g gulp bower

# Dirs
RUN mkdir /source
RUN mkdir -p /data/db

ADD project /source/project
ADD build.sbt /source/build.sbt
ADD client/bower.json /source/client/bower.json
ADD client/gulpfile.js /source/client/gulpfile.js
ADD client/package.json /source/client/package.json
ADD client/wct.conf.js /source/client/wct.conf.js
ADD client/test.html /source/client/test.html
ADD run_tests.sh /source/run_tests.sh

# Dependencies
RUN cd /source && \
    sbt -Dhttps.proxyHost=192.168.22.1 -Dhttps.proxyPort=3129 -Dhttp.proxyHost=192.168.22.1 -Dhttp.proxyPort=3129 update

RUN cd /source/client && \
    git config --global http.proxy http://192.168.22.1:3129 && \
    git config --global https.proxy http://192.168.22.1:3129 && \
    git config --global url."https://".insteadOf git:// && \
    HTTP_PROXY=http://192.168.22.1:3129 && \
    HTTPS_PROXY=http://192.168.22.1:3129 && \
    http_proxy=http://192.168.22.1:3129 && \
    https_proxy=http://192.168.22.1:3129 && \
    npm config set strict-ssl false && \
    npm install && \
    bower install --allow-root --config.interactive=false -s

# Envs
ENV HTTP_PROXY "http://192.168.22.1:3129"
ENV HTTPS_PROXY "http://192.168.22.1:3129"
ENV http_proxy "http://192.168.22.1:3129"
ENV https_proxy "http://192.168.22.1:3129"
ENV TEST_TYPE "spec"
ENV DOMAIN "http://172.17.42.1"
ENV DISPLAY ":1.0"
ENV DB_HOST localhost

WORKDIR /source
VOLUME ["/source", "/source/target/scala-2.10", "/root/.ivy2/cache", "/data/db"]


CMD ["/source/run_tests.sh"]

EXPOSE 8080

