FROM 10.100.198.200:5000/books-ms-tests_0
MAINTAINER Viktor Farcic "viktor@farcic.com"

ENV VERSION 1.0

# Envs
ENV HTTP_PROXY "http://192.168.22.1:3129"
ENV HTTPS_PROXY "http://192.168.22.1:3129"
ENV http_proxy "http://192.168.22.1:3129"
ENV https_proxy "http://192.168.22.1:3129"
ENV TEST_TYPE "spec"
ENV DOMAIN "http://172.17.42.1"
ENV DISPLAY ":1.0"
ENV DB_HOST localhost

WORKDIR /source
VOLUME ["/source", "/source/target/scala-2.10", "/root/.ivy2/cache", "/data/db"]

CMD ["/source/run_tests.sh"]

EXPOSE 8080

